import { defineConfig, type Plugin } from 'vite'
import vue from '@vitejs/plugin-vue'
import VueRouter from 'unplugin-vue-router/vite'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import { VueRouterAutoImports } from 'unplugin-vue-router'
import { fileURLToPath, URL } from 'node:url'
import { BRAND } from './src/brand'
import {
  APP_AUTH_ROUTES,
  DEFAULT_LOCALE,
  LOCALES,
  MARKETING_ORIGIN,
  MARKETING_PAGES,
  MARKETING_ROUTES,
  localizedPath,
} from './src/router/public-routes'

function robotsTxt(): string {
  return [
    '# Block everything by default; only the public pages below are crawlable.',
    '# This way new authenticated/app routes stay out of search automatically.',
    '# Generated by vite.config.ts from src/router/public-routes.ts.',
    '',
    'User-agent: *',
    'Disallow: /',
    '',
    '# Public pages. Marketing pages are localized as /<locale>/<slug>.',
    '# "/$" matches only the bare root (which redirects to the locale home).',
    'Allow: /$',
    ...LOCALES.map((locale) => `Allow: /${locale}/`),
    ...APP_AUTH_ROUTES.map((path) => `Allow: ${path}`),
    '',
    "# Static assets the SPA needs in order to render (don't block these).",
    'Allow: /assets/',
    'Allow: /favicon.svg',
    'Allow: /logo.png',
    'Allow: /og-image.png',
    'Allow: /sitemap.xml',
    '',
    `Sitemap: ${MARKETING_ORIGIN}/sitemap.xml`,
    '',
  ].join('\n')
}

function sitemapXml(): string {
  const urls = MARKETING_PAGES.flatMap((page) =>
    LOCALES.map((locale) => {
      const alternates = [
        ...LOCALES.map((alt) => ({ hreflang: alt, path: localizedPath(page, alt) })),
        { hreflang: 'x-default', path: localizedPath(page, DEFAULT_LOCALE) },
      ]
        .map(
          ({ hreflang, path }) =>
            `    <xhtml:link rel="alternate" hreflang="${hreflang}" href="${MARKETING_ORIGIN}${path}"/>`,
        )
        .join('\n')
      return [
        '  <url>',
        `    <loc>${MARKETING_ORIGIN}${localizedPath(page, locale)}</loc>`,
        alternates,
        '    <changefreq>weekly</changefreq>',
        `    <priority>${page.key === 'home' ? '1.0' : '0.8'}</priority>`,
        '  </url>',
      ].join('\n')
    }),
  )
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    ...urls,
    '</urlset>',
    '',
  ].join('\n')
}

/**
 * Brand-dependent static output: fills the `%BRAND_NAME%` / `%MARKETING_ORIGIN%`
 * placeholders in index.html and emits robots.txt + sitemap.xml, so neither
 * the domain nor the product name is hard-coded outside `src/brand.ts`.
 */
function brandAssets(): Plugin {
  let isSsrBuild = false
  return {
    name: 'brand-assets',
    configResolved(config) {
      isSsrBuild = Boolean(config.build.ssr)
    },
    transformIndexHtml(html) {
      return html
        .replace(/%BRAND_NAME%/g, BRAND.name)
        .replace(/%MARKETING_ORIGIN%/g, MARKETING_ORIGIN)
    },
    generateBundle() {
      if (isSsrBuild) return
      this.emitFile({ type: 'asset', fileName: 'robots.txt', source: robotsTxt() })
      this.emitFile({ type: 'asset', fileName: 'sitemap.xml', source: sitemapXml() })
    },
  }
}

export default defineConfig({
  // Prerender the marketing pages to static HTML. `try_files $uri $uri/
  // /index.html` in nginx.conf.template already serves dist/<route>/index.html,
  // so this needs no server change. Every other route falls back to the SPA
  // shell exactly as before.
  ssgOptions: {
    script: 'async',
    formatting: 'minify',
    // '/' is a redirect route (see src/router/index.ts): vite-ssg follows it to
    // the default locale and writes that render to dist/index.html, so the site
    // root ships real HTML instead of the bare SPA shell. The canonical tag it
    // emits points at /da/, so this adds no duplicate content.
    includedRoutes: () => ['/', ...MARKETING_ROUTES],
    // One page at a time. `plugins/i18n.ts` exports a single i18n instance that
    // every prerendered page shares, and the router guard switches its locale
    // per route - so rendering pages in parallel (vite-ssg defaults to 20) lets
    // the last guard to run decide the language for all of them, and every page
    // comes out in whichever locale finished last.
    concurrency: 1,
  },
  // Vue SFC deps ship ESM that Node can't require during the prerender pass;
  // let Vite bundle them into the SSR build instead.
  ssr: {
    noExternal: [
      'reka-ui',
      'radix-vue',
      'lucide-vue-next',
      '@vueuse/core',
      '@vueuse/shared',
      'vee-validate',
      '@vee-validate/zod',
      'class-variance-authority',
      'tailwind-merge',
    ],
  },
  plugins: [
    brandAssets(),
    VueRouter({
      routesFolder: ['src/platform/pages', 'src/example/pages'],
      dts: 'src/typed-router.d.ts',
    }),
    vue(),
    AutoImport({
      imports: [
        'vue',
        VueRouterAutoImports,
        { pinia: ['defineStore', 'storeToRefs'] },
        { '@vueuse/core': ['useDark', 'useToggle', 'useLocalStorage', 'useMediaQuery'] },
      ],
      dts: 'src/auto-imports.d.ts',
      vueTemplate: true,
    }),
    Components({
      dirs: ['src/platform/components', 'src/example/components'],
      dts: 'src/components.d.ts',
    }),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    proxy: {
      '/v1': {
        target: process.env.API_TARGET ?? 'http://localhost:8000',
        changeOrigin: true,
      },
    },
  },
})
